Repository Kotlin/dokka, pull requests merged in 2020-07, with the labels that each got.

#1026 Show fully qualified name for typealias targeting different package
  plugins/base/src/main/kotlin/signatures/KotlinSignatureProvider.kt
  plugins/base/src/main/kotlin/signatures/KotlinSignatureUtils.kt
  plugins/base/src/test/kotlin/content/signatures/ContentForSignaturesTest.kt
  plugins/base/src/test/kotlin/utils/contentUtils.kt
Labels: libs feedback

#1061 Fix racecondition on caching of external providers
  plugins/base/src/main/kotlin/resolvers/external/ExternalLocationProviderFactory.kt
Labels: bug

#1082 Fix concurrency issue managing package request cache
  plugins/base/src/main/kotlin/resolvers/local/BaseLocationProvider.kt
Labels: bug

#1090 Fix NPE
  plugins/base/src/main/kotlin/translators/psi/DefaultPsiToDocumentableTranslator.kt
Labels: bug

#1089 Fix crash resolving PsiDocTagValue
  kotlin-analysis/src/main/kotlin/org/jetbrains/dokka/analysis/AnalysisEnvironment.kt
Labels: bug

#1160 Only register collector and multimodule tasks on projects that actually have children
  runners/gradle-plugin/src/main/kotlin/org/jetbrains/dokka/gradle/main.kt
Labels: enhancement

#1161 Use kotlin "1.4-M3" artifact
  gradle.properties
  integration-tests/gradle/src/integrationTest/kotlin/org/jetbrains/dokka/it/gradle/Android0GradleIntegrationTest.kt
  integration-tests/gradle/src/integrationTest/kotlin/org/jetbrains/dokka/it/gradle/BasicGradleIntegrationTest.kt
  integration-tests/gradle/src/integrationTest/kotlin/org/jetbrains/dokka/it/gradle/BasicGroovyIntegrationTest.kt
  integration-tests/gradle/src/integrationTest/kotlin/org/jetbrains/dokka/it/gradle/Multimodule0IntegrationTest.kt
  integration-tests/gradle/src/integrationTest/kotlin/org/jetbrains/dokka/it/gradle/Multiplatform0GradleIntegrationTest.kt
Labels: enhancement

#1181 Remove old runners/xml folder
  plugins/xml/build.gradle.kts
  plugins/xml/src/main/kotlin/XmlPlugin.kt
  plugins/xml/src/main/kotlin/utils.kt
  plugins/xml/src/main/resources/META-INF/services/org.jetbrains.dokka.plugability.DokkaPlugin
Labels: enhancement

#1182 Upgrade kotlinx-html to 0.7.1-1.4-M3
  gradle.properties
  plugins/base/build.gradle.kts
  plugins/javadoc/build.gradle.kts
Labels: enhancement

#1225 Fix error message when no dokka source sets are registered
  runners/gradle-plugin/src/main/kotlin/org/jetbrains/dokka/gradle/DokkaTask.kt
Labels: enhancement
