Repository Kotlin/dokka, pull requests merged in 2020-09, with the labels that each got.

#1417 Also add KotlinCompile#classpath to final classpath calculation
  runners/gradle-plugin/src/main/kotlin/org/jetbrains/dokka/gradle/kotlin/kotlinClasspathUtils.kt
Labels: Gradle Plugin, bug, high priority

#1420 Add whitespace in parameters of classlike signature
  plugins/base/src/main/kotlin/signatures/KotlinSignatureProvider.kt
Labels: html frontend

#1430 Update Dokka maturity warning
  core/src/main/kotlin/printDokkaMaturityWarning.kt
Labels: enhancement

#1435 Support multiple publication channels at once
  buildSrc/src/main/kotlin/org/jetbrains/DokkaPublicationChannel.kt
  buildSrc/src/main/kotlin/org/jetbrains/ValidatePublications.kt
  buildSrc/src/main/kotlin/org/jetbrains/publication.kt
  gradle.properties
Labels: infrastructure

#1295 Adding missing subclasses pages
  .idea/codeStyles/Project.xml
  plugins/javadoc/src/main/kotlin/org/jetbrains/dokka/javadoc/JavadocPageCreator.kt
  plugins/javadoc/src/main/kotlin/org/jetbrains/dokka/javadoc/pages/htmlPreprocessors.kt
  plugins/javadoc/src/main/kotlin/org/jetbrains/dokka/javadoc/renderer/JavadocContentToTemplateMapTranslator.kt
  plugins/javadoc/src/main/kotlin/org/jetbrains/dokka/javadoc/renderer/SearchScriptsCreator.kt
  plugins/javadoc/src/main/kotlin/org/jetbrains/dokka/javadoc/signatures/JavadocSignatureProvider.kt
  plugins/javadoc/src/main/resources/views/class.korte
  plugins/javadoc/src/test/kotlin/org/jetbrains/dokka/javadoc/JavadocIndexTest.kt
Labels: Javadoc
