Repository Kotlin/dokka, pull requests merged in 2020-08, with the labels that each got.

#1251 Add more formats to Multimodule0IntegrationTest.kt
  integration-tests/gradle/src/integrationTest/kotlin/org/jetbrains/dokka/it/gradle/Multimodule0IntegrationTest.kt
Labels: enhancement

#1315 Update Gradle version to 6.6
  gradle/wrapper/gradle-wrapper.properties
  integration-tests/gradle/projects/it-multiplatform-0/build.gradle.kts
  integration-tests/gradle/projects/it-multiplatform-0/gradle.properties
  integration-tests/gradle/src/integrationTest/kotlin/org/jetbrains/dokka/it/gradle/Android0GradleIntegrationTest.kt
  integration-tests/gradle/src/integrationTest/kotlin/org/jetbrains/dokka/it/gradle/BasicGradleIntegrationTest.kt
  integration-tests/gradle/src/integrationTest/kotlin/org/jetbrains/dokka/it/gradle/BasicGroovyIntegrationTest.kt
  integration-tests/gradle/src/integrationTest/kotlin/org/jetbrains/dokka/it/gradle/Collector0IntegrationTest.kt
  integration-tests/gradle/src/integrationTest/kotlin/org/jetbrains/dokka/it/gradle/MultiModule0IntegrationTest.kt
  integration-tests/gradle/src/integrationTest/kotlin/org/jetbrains/dokka/it/gradle/Multiplatform0GradleIntegrationTest.kt
  runners/gradle-plugin/src/test/kotlin/org/jetbrains/dokka/gradle/DokkaCollectorTaskTest.kt
Labels: infrastructure

#1312 Print maturity warning when running dokka
  core/src/main/kotlin/DokkaGenerator.kt
  core/src/main/kotlin/printDokkaMaturityWarning.kt
Labels: enhancement

#1347 Mitigate issue `Couldn't get delegate for class`
  plugins/base/src/main/kotlin/translators/psi/DefaultPsiToDocumentableTranslator.kt
  plugins/base/src/test/kotlin/translators/Bug1341.kt
Labels: bug, high priority

#1352 Fix convention for ExternalDocumentationLink#packageListUrl
  integration-tests/gradle/projects/it-multiplatform-0/build.gradle.kts
  runners/gradle-plugin/src/main/kotlin/org/jetbrains/dokka/gradle/GradleExternalDocumentationLinkBuilder.kt
Labels: Gradle Plugin

#1353 Add task descriptions to all dokka tasks
  runners/gradle-plugin/src/main/kotlin/org/jetbrains/dokka/gradle/main.kt
  runners/gradle-plugin/src/test/kotlin/org/jetbrains/dokka/gradle/DokkaPluginApplyTest.kt
Labels: Gradle Plugin, enhancement

#1349 Update dokka README.md to reflect changes for 1.4.0
  README.md
Labels: enhancement

#1369 Set cursor value to pointer for various buttons
  plugins/base/frontend/src/main/components/search/search.scss
  plugins/base/src/main/resources/dokka/styles/style.css
Labels: enhancement, html frontend

#1372 Relative paths fix
  runners/cli/src/main/kotlin/cli/main.kt
Labels: bug

#1395 Fixing top-level functions linking for javadoc
  plugins/javadoc/src/main/kotlin/org/jetbrains/dokka/javadoc/location/JavadocLocationProvider.kt
  plugins/javadoc/src/main/kotlin/org/jetbrains/dokka/javadoc/pages/JavadocPageNodes.kt
  plugins/javadoc/src/main/kotlin/org/jetbrains/dokka/javadoc/pages/htmlPreprocessors.kt
  plugins/javadoc/src/main/resources/views/class.korte
Labels: bug, high priority, regression

#1401 Missing javadoc resources on windows
  plugins/javadoc/src/main/kotlin/org/jetbrains/dokka/javadoc/renderer/JavadocContentToTemplateMapTranslator.kt
  plugins/javadoc/src/test/kotlin/org/jetbrains/dokka/javadoc/JavadocLocationTemplateMapTest.kt
Labels: regression

#1404 Hide navigation pane search on multimodule page
  plugins/base/frontend/src/main/components/root.tsx
  plugins/base/src/main/kotlin/renderers/html/HtmlRenderer.kt
Labels: enhancement
