Repository Kotlin/dokka, pull requests merged in 2024-07, with the labels that each got.

#3470 build: extracted UI components to ui-kit in plugin-base-frontend
  .gitignore
  .husky/pre-commit
  .idea/codeStyles/Project.xml
  dokka-subprojects/plugin-base-frontend/.eslintrc.js
  dokka-subprojects/plugin-base-frontend/.prettierrc.js
  dokka-subprojects/plugin-base-frontend/lint-staged.config.js
  dokka-subprojects/plugin-base-frontend/package-lock.json
  dokka-subprojects/plugin-base-frontend/package.json
  dokka-subprojects/plugin-base-frontend/src/main/components/app/index.scss
  dokka-subprojects/plugin-base-frontend/src/main/components/app/index.tsx
  dokka-subprojects/plugin-base-frontend/src/main/components/root.tsx
  dokka-subprojects/plugin-base-frontend/src/main/components/search/dokkaFuzzyFilter.tsx
  dokka-subprojects/plugin-base-frontend/src/main/components/search/dokkaSearchAnchor.tsx
  dokka-subprojects/plugin-base-frontend/src/main/components/search/search.scss
  dokka-subprojects/plugin-base-frontend/src/main/components/search/search.tsx
  dokka-subprojects/plugin-base-frontend/src/main/components/search/searchResultRow.tsx
  dokka-subprojects/plugin-base-frontend/src/main/components/search/types.ts
  dokka-subprojects/plugin-base-frontend/src/main/components/utils/hotkey.ts
  dokka-subprojects/plugin-base-frontend/src/main/components/utils/os.ts
  dokka-subprojects/plugin-base-frontend/src/main/components/utils/requests.tsx
  dokka-subprojects/plugin-base-frontend/src/main/scss/index.scss
  dokka-subprojects/plugin-base-frontend/src/main/types/@jetbrains/index.d.ts
  dokka-subprojects/plugin-base-frontend/src/main/ui-kit/index.scss
  dokka-subprojects/plugin-base-frontend/src/main/ui-kit/index.ts
  dokka-subprojects/plugin-base-frontend/src/main/ui-kit/tabs/index.ts
  dokka-subprojects/plugin-base-frontend/src/main/ui-kit/tabs/styles.scss
  dokka-subprojects/plugin-base-frontend/stylelint.config.js
  dokka-subprojects/plugin-base-frontend/tsconfig.json
  dokka-subprojects/plugin-base-frontend/webpack.config-ui-kit.js
  dokka-subprojects/plugin-base/src/main/kotlin/org/jetbrains/dokka/base/renderers/html/htmlPreprocessors.kt
  dokka-subprojects/plugin-base/src/main/resources/dokka/scripts/platform-content-handler.js
  dokka-subprojects/plugin-base/src/main/resources/dokka/styles/style.css
  dokka-subprojects/plugin-base/src/main/resources/dokka/ui-kit/ui-kit.css
  dokka-subprojects/plugin-base/src/main/resources/dokka/ui-kit/ui-kit.min.css
  dokka-subprojects/plugin-base/src/main/resources/dokka/ui-kit/ui-kit.min.js
Labels: format: html, infrastructure, html: frontend

#3713 Update Gradle to v8.9
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
Labels: infrastructure

#3710 Exclude `build-settings-logic` from included-build tasks workaround
  build.gradle.kts
Labels: infrastructure

#3712 Update GitCheckoutTask, so it re-runs if the repo is dirty
  build-logic/src/main/kotlin/dokkabuild/tasks/GitCheckoutTask.kt
Labels: infrastructure

#3720 build: added dev server for ui kit development
  dokka-subprojects/plugin-base-frontend/README.md
  dokka-subprojects/plugin-base-frontend/create-component.mjs
  dokka-subprojects/plugin-base-frontend/package-lock.json
  dokka-subprojects/plugin-base-frontend/package.json
  dokka-subprojects/plugin-base-frontend/postcss.config.js
  dokka-subprojects/plugin-base-frontend/stylelint.config.js
  dokka-subprojects/plugin-base-frontend/webpack.config-ui-kit.js
Labels: enhancement, format: html, UI Kit
