Repository Kotlin/dokka, pull requests merged in 2025-05, with the labels that each got.

#3791 Update Develocity plugin to support "Resource usage observability in Build Scan"
  gradle/libs.versions.toml
Labels: infrastructure

#4091 Fix typo in dev docs
  docs-developer/docs/developer_guide/architecture/data_model/page_content.md
Labels: documentation

#3899 Drop kotlinx.serialization compiler plugin as it's unnecessary
  dokka-runners/dokka-gradle-plugin/api/dokka-gradle-plugin.api
  dokka-runners/dokka-gradle-plugin/build.gradle.kts
  dokka-runners/dokka-gradle-plugin/src/main/kotlin/engine/parameters/DokkaModuleDescriptionKxs.kt
  dokka-runners/dokka-gradle-plugin/src/main/kotlin/engine/parameters/builders/DokkaParametersBuilder.kt
  dokka-runners/dokka-gradle-plugin/src/main/kotlin/tasks/DokkaGenerateModuleTask.kt
  dokka-runners/dokka-gradle-plugin/src/test/kotlin/engine/parameters/DokkaModuleDescriptionKxsTest.kt
Labels: runner: Gradle plugin
